### ISSUE TITLE
error returned from SetGraceTime is ignored

### ISSUE THREAD

**Issue by stefanschneider** [cloudfoundry-incubator/garden#41]
The garden server ignores the error form the SetGraceTime call:
https://github.com/cloudfoundry-incubator/garden/blob/master/server/request_handling.go#L867

**Comment by julz** [comment]
ah, yeah, I think the errors on `SetGraceTime` were added just in order to be able for garden to return an error to the client (we had to add the errors to both since the same interface is used for the client and the backend implementation of Container), we never envisaged the backend wanting to return an error from this (or from GraceTime, as you've noticed in #42). I'd be totally fine with a pull request that allowed the backend to return an error from these calls.

**Comment by julz** [comment]
Im going to close this and https://github.com/cloudfoundry-incubator/garden/issues/42 because I don't think we plan to work on this ourselves in the near future, but we'd be happy to accept a pull request that added this.
